# File content filtering

## File Filtering 

### Column filtering

### `cut`

`cut` can be used to print selected parts of lines from each FILE to standard output.

cut sort uniq wc grep 


https://www.youtube.com/playlist?list=PLtK75qxsQaMLZSo7KL-PmiRarU7hrpnwK


### Row filtering

#### `grep`


---------------------

The `grep` command which stands for “global regular expression print,” processes text line by line and prints any lines which match a specified pattern. The grep command is used to search text or searches the given file for lines containing a match to the given strings or words. By default, grep displays the matching lines. 

```{sh}
grep 'WRKY' data/gene_annotation.txt
```

```{sh}
grep 'WRKY' data/gene_annotation.txt  |wc -l 
```


```{sh}
grep -i 'WRKY' data/gene_annotation.txt 
```

If you want to search for a word, and avoid matching substrings use ‘-w ‘option.

```{sh}
grep 'gene1' data/gene_annotation.txt 
```

```{sh}
grep -w 'gene1' data/gene_annotation.txt 
```

#### `awk`

## `paste`

```{sh}
paste data/DEG_list.txt data/gene_annotation.txt |head -5
```

```{sh}
paste data/DEG_list.txt data/gene_annotation.txt |head -5 |cut -f 1-3,5
```


```{sh}
head -2 data/WGBS_example_data/EV1.fastq
```

```{sh}
paste - - - - <data/WGBS_example_data/EV1.fastq |head -2 
```

```{sh}
paste - - - - <data/WGBS_example_data/EV1.fastq |cut -f1-2 |head -2
```

Convert fastq file to fasta file using paste: 

```{sh}
paste - - - - <data/WGBS_example_data/EV1.fastq |cut -f1-2 | sed 's/^@/>/' | tr "\t" "\n"  |head -4
```

## Finding Things

### Find files with pattern matching


```{sh}
## Find any files with "Linux" and ".Rmd" in the file names
find . -type f -name "*Linux*.Rmd"
```

### Count file numbers in a  folder and its subdirectories

```{sh}
find . -type f | wc -l
```

### List files bigger than filesize specified

```{sh}
#To find files larger than 10MB:
find . -type f -size +10M
```

```{sh}
# If you want the current dir only:
find . -maxdepth 1 -type f -size +1M
```

### Find files and do someting

```{sh}
find . -type f -name "*fa*.pl" -exec ls -l {} +; 
```


## Check you job status


```
$ ps aux  
USER       PID  %CPU %MEM  VSZ RSS     TTY   STAT START   TIME COMMAND
timothy  29217  0.0  0.0 11916 4560 pts/21   S+   08:15   0:00 pine  
root     29505  0.0  0.0 38196 2728 ?        Ss   Mar07   0:00 sshd: can [priv]   
can      29529  0.0  0.0 38332 1904 ?        S    Mar07   0:00 sshd: can@notty  
```

USER = user owning the process
PID = process ID of the process
%CPU = It is the CPU time used divided by the time the process has been running.
%MEM = ratio of the process’s resident set size to the physical memory on the machine
VSZ = virtual memory usage of entire process (in KiB)
RSS = resident set size, the non-swapped physical memory that a task has used (in KiB)
TTY = controlling tty (terminal)
STAT = multi-character process state
START = starting time or date of the process
TIME = cumulative CPU time
COMMAND = command with all its arguments

References:

https://superuser.com/questions/117913/ps-aux-output-meaning
