# (PART) Statistics and R {-}

# R introduction

## Basic R function

## Producing Simple Graphs with R

The credit of this section goes to Dr. Frank McCown (@simpleGraphR). 

### Line Charts

```{r}
# Define the cars vector with 5 values
cars <- c(1, 3, 6, 4, 9)

# Graph the cars vector with all defaults
plot(cars)
?plot
```


Let's add a title, a line to connect the points, and some color:

```{r}
# Define the cars vector with 5 values
cars <- c(1, 3, 6, 4, 9)

# Graph cars using blue points overlayed by a line 
plot(cars, type="o", col="blue")

# Create a title with a red, bold/italic font
title(main="Autos", col.main="red", font.main=4)
```

Now let's add a red line for trucks and specify the y-axis range directly so it will be large enough to fit the truck data:


```{r}
# Define 2 vectors
cars <- c(1, 3, 6, 4, 9)
trucks <- c(2, 5, 4, 5, 12)

# Graph cars using a y axis that ranges from 0 to 12
plot(cars, type="o", col="blue", ylim=c(0,12))

# Graph trucks with red dashed line and square points
lines(trucks, type="o", pch=22, lty=2, col="red")

# Create a title with a red, bold/italic font
title(main="Autos", col.main="red", font.main=4)
```



## XXX


```{r}
fruit = c("apple", "apple", "pear", "orange")
fruit == "apple" 
```
```{r}
fruit = c("apple", "apple", "pear", "orange")
which(fruit == "apple")
```


```{r}
fruit = c("apple", "apple", "pear", "orange")
which(fruit == "apple" | fruit == "pear")
```



