# (PART) Omics data {-}

# Introduction to NGS 


## Introduction of Biology for Bioinformatics



###  What is DNA 

### What is genome

### How to assemble a genome

### What is gene 



## What is NGS

Genetic information is stored within the chemical structure of the molecule DNA. DNA can be transcribed into RNA. Then RNA can be translated into protein. 

NGS (Next geneneration sequencing) is not an accurate term. An more accurate term maybe high throughput sequencing.  NGS is specifically used to refer to sequencing technologies after Sanger sequencing (1st generation) and single molecular sequencing (3rd sequencing, e.g. PacBio) and nanopore based sequencing (4th generation, e.g. Oxford Nanopore).



## Application of NGS

## 




## Data file formats to store the genomic information

### `fasta` file 

### GFF file

### GTF file 

### FASTQ file

### SAM/BAM file

### VCF file

### BED format

### bedGraph format




## Usefull links:

http://www.ecseq.com/support/ngs/trimming-adapter-sequences-is-it-necessary

http://www.gendx.com/illumina-adapter-ligation-librx

http://veleta.rosety.com/plasmid.html





