mv 00_about_me_acknowledge.Rmd 00_about_me_acknowledge.Rmd
mv 01_WhyLinux.Rmd 01_WhyLinux.Rmd
mv 02_Connect2Linux.Rmd 02_Connect2Linux.Rmd
mv 03_FileSystemLinux.Rmd 03_FileSystemLinux.Rmd
mv 04_Linux_FilteringOutputandFindingThings.Rmd 04_Linux_FilteringOutputandFindingThings.Rmd
mv 05_AchivingAndCompressingFiles.Rmd 05_AchivingAndCompressingFiles.Rmd
mv 06_procManageLinux.Rmd 06_procManageLinux.Rmd
mv 07_fileTransfer.Rmd 07_fileTransfer.Rmd
mv 08_InstallationOfSoftwareInLinux.Rmd 08_InstallationOfSoftwareInLinux.Rmd
mv 09_TextEditorInLinux.Rmd 09_TextEditorInLinux.Rmd
mv 11_FirstPerlProgram.Rmd 10_FirstPerlProgram.Rmd
mv 12_PerlArrat.Rmd 11_PerlArrat.Rmd
mv 13_PerlVariableOperator.Rmd 12_PerlVariableOperator.Rmd
mv 14_PerlControlStructure.Rmd 13_PerlControlStructure.Rmd
mv 15_StringManipulationRegExp.Rmd 14_StringManipulationRegExp.Rmd
mv 16_PerlInputOutput.Rmd 15_PerlInputOutput.Rmd
mv 17_practicalPerlProgram.Rmd 16_practicalPerlProgram.Rmd
mv 18_PerlModules.Rmd 17_PerlModules.Rmd
mv 19_R_intro.Rmd 18_R_intro.Rmd
mv 20_SimpleGraphR.Rmd 19_SimpleGraphR.Rmd
mv 21_GraphGgplot2.Rmd 20_GraphGgplot2.Rmd
mv 22_GenerateHeatmap.Rmd 21_GenerateHeatmap.Rmd
mv 23_FigureManuscript.Rmd 22_FigureManuscript.Rmd
mv 24_IntroNGS.Rmd 23_IntroNGS.Rmd
mv 25_introRNA-seq.Rmd 24_introRNA-seq.Rmd
mv 26_introChIP-seq.Rmd 25_introChIP-seq.Rmd
mv 27_introBSseq.Rmd 26_introBSseq.Rmd
mv 28_ExpDesign.Rmd 27_ExpDesign.Rmd
mv 29_CapstoneProjectRNA-seq.Rmd 28_CapstoneProjectRNA-seq.Rmd
mv 30_CapstoneProjectChIP-seq.Rmd 29_CapstoneProjectChIP-seq.Rmd
mv 31_CapstoneProjectBS-seq.Rmd 30_CapstoneProjectBS-seq.Rmd
mv 32_Good_resource.Rmd 31_Good_resource.Rmd
mv 33_Reference.Rmd 32_Reference.Rmd
